- type: job
  id: NanotrasenRepresentative
  name: представитель NanoTrasen
  description: "Представляйте НТ, отправляйте им отчёты о ситуации на станции, информируйте глав о любых действиях, которые им приказывает выполнить ЦентКом."
  playTimeTracker: JobNanotrasenRepresentative
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Command
      min: 54000 # 15 hours
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
    - !type:CharacterEmployerRequirement
      employers:
      - NanoTrasen
    - !type:CharacterDepartmentTimeRequirement
      department: Orehum
      min: 5 # Снять после достижения более стабильного онлайна
  weight: 20
  startingGear: NanotrasenRepresentativeGear
  icon: "JobIconNanotrasenRepresentative"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - CentralCommand
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - NanotrasenRepresentative
  - Lawyer
  - Cargo
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: NanotrasenRepresentativeGear
  subGear:
  - NanotrasenRepresentativePlasmamanGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: CentcomPDA
    jumpsuit: ClothingUniformJumpsuitNanotrasenRepresentative
    ears: ClothingHeadsetAltCentCom
    pocket1: UniqueNanorepLockerTeleporter

- type: startingGear
  id: NanotrasenRepresentativePlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitNanotrasenRepresentative
    head: ClothingHeadEnvirohelmNanotrasenRepresentative
    gloves: ClothingHandsGlovesEnviroglovesBlack
